services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - docker-variables-db.env
    ports:
      - '5432:5432'

  app:
    container_name: arquivos-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - docker-variables-spring-application.env
    depends_on:
      - db

  angular-app:
    container_name: angular-app
    build:
      context: D:\essia-arquivos-angular  # Point to the Angular app directory
      dockerfile: Dockerfile           # Dockerfile for Angular app
    ports:
      - '4200:80'                      # Expose Angular app on port 4200
    depends_on:
      - app                            # Ensure Spring Boot app starts first